/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autenticación de usuario (emite JWT con rol)
         * @description Credenciales válidas → sesión autenticada con rol (FR-026). Credenciales inválidas → 401 con mensaje genérico que no revela si falló usuario o contraseña (FR-027).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cierre de sesión del usuario autenticado
         * @description Finaliza la sesión; se requiere login de nuevo para funciones protegidas (FR-029).
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista únicamente las órdenes asignadas al usuario autenticado
         * @description No devuelve órdenes de otros usuarios (lista vacía si no tiene ninguna).
         */
        get: operations["listMyOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        /**
         * Detalle de una orden asignada al usuario
         * @description 404 si la orden no está asignada al usuario (no se revela existencia).
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/execution": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * El técnico asignado registra y envía la ejecución
         * @description Requiere ≥1 foto JPEG ≤10 MB (máx 15), ubicación, firma y duración del trabajo. Transiciona la orden a "Enviada". Solo el técnico asignado (rol técnico).
         */
        post: operations["submitExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/reassignment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * El dispatcher reasigna la orden a otro técnico
         * @description Permitida solo si la orden no está Aprobada. Solo rol dispatcher.
         */
        post: operations["reassignOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        /**
         * El supervisor abre una ejecución enviada para revisión (incluye resumen de incidencia)
         * @description Devuelve la ejecución con el resumen de incidencia generado desde las notas (FR-017). Si el resumen no está disponible, incluye las notas como fallback. Solo rol supervisor.
         */
        get: operations["openReview"];
        put?: never;
        /**
         * El supervisor aprueba o rechaza la ejecución enviada
         * @description approve → Aprobada (FR-008); reject → Rechazada, disponible para reenvío (FR-009). Solo rol supervisor; en caso contrario 403 y la orden permanece en su estado previo.
         */
        post: operations["decideReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "tecnico" | "dispatcher" | "supervisor";
        /** @enum {string} */
        OrderState: "Asignada" | "EnEjecucion" | "Enviada" | "Aprobada" | "Rechazada";
        LoginRequest: {
            username: string;
            password: string;
        };
        AuthToken: {
            token: string;
            role: components["schemas"]["Role"];
        };
        Material: {
            description: string;
            quantity: number;
            price: number;
        };
        WorkOrder: {
            /** Format: uuid */
            id: string;
            customer: string;
            address: string;
            service: string;
            /** Format: date */
            date: string;
            /** Format: uuid */
            assignedTechnicianId: string;
            state: components["schemas"]["OrderState"];
            materials?: components["schemas"]["Material"][];
        };
        ExecutionSubmission: {
            technicianNotes?: string;
            /** @description Ubicación de la ejecución (obligatoria, FR-015) */
            location: string;
            /**
             * Format: binary
             * @description Firma (obligatoria, FR-015)
             */
            signature: string;
            /** @description Tiempo de trabajo (FR-016) */
            workDurationMinutes: number;
            /** @description Fotos JPEG ≤10 MB (FR-003/004/014) */
            photos: string[];
        };
        ReassignRequest: {
            /** Format: uuid */
            toTechnicianId: string;
        };
        ReviewDecision: {
            /** @enum {string} */
            outcome: "approve" | "reject";
            comment?: string;
        };
        ReviewView: {
            order: components["schemas"]["WorkOrder"];
            technicianNotes?: string;
            incidentSummary: components["schemas"]["IncidentSummary"];
        };
        /** @description Resumen de incidencia (FR-017/023/024/025); contrato en contracts/ai/incident-summary.contract.md */
        IncidentSummary: {
            /**
             * @description insufficient_evidence=abstención (FR-023); provider_failed=fallback a notas (FR-025)
             * @enum {string}
             */
            status: "ok" | "insufficient_evidence" | "provider_failed";
            /** @description Puntos clave; cada uno referencia el fragmento de nota que lo respalda (grounding, FR-024) */
            keyPoints: {
                text: string;
                sourceNoteFragment: string;
            }[];
        };
        Error: {
            code: string;
            message: string;
        };
    };
    responses: {
        /** @description No autenticado */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Autenticado pero sin rol autorizado (403) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Recurso no encontrado o no asignado al usuario (404) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        OrderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthToken"];
                };
            };
            /** @description Credenciales inválidas — mensaje genérico, sin sesión (FR-027) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión finalizada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMyOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Órdenes del usuario (posiblemente vacía) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orden */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    submitExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ExecutionSubmission"];
            };
        };
        responses: {
            /** @description Ejecución registrada; orden en estado Enviada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            /** @description Envío inválido — sin foto (FR-003), foto no JPEG o >10 MB (FR-014), o sin ubicación/firma (FR-015). La orden permanece en su estado previo. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reassignOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReassignRequest"];
            };
        };
        responses: {
            /** @description Reasignada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Actor sin rol dispatcher (FR-019) o orden ya Aprobada (FR-006). Técnico sin cambios. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    openReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ejecución con resumen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    decideReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecision"];
            };
        };
        responses: {
            /** @description Decisión aplicada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
